# Generated by Django 4.0.1 on 2022-04-02 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmes',
            options={'verbose_name_plural': 'Programmes'},
        ),
    ]
